### ISSUE TITLE
spm_sample_vol 'Bug' in ft_warp_apply

### ISSUE THREAD

**Issue by linrongqi** [fieldtrip/fieldtrip#1725]
Hey FT community,
I want to use the ft_warp_apply to tranform the subject's coordinate into MNI.
When i use the fuction 'ft_warp_apply' , there was a bug
##########
elec_mni = elec_acpc_fr;
elec_mni.elecpos = ft_warp_apply(fsmri_mni.params, elec_acpc_fr.elecpos, 'individual2sn');
elec_mni.chanpos = ft_warp_apply(fsmri_mni.params, elec_acpc_fr.chanpos, 'individual2sn');
elec_mni.coordsys = 'mni';
###########
##########
Wrong use spm_sample_vol
File too small.
Error in spm_preproc_write8 (line 182)
 f          = spm_sample_vol(res.image(n),x1,x2,o*x3(z),0);
Error in individual2sn (line 81)
 spm_preproc_write8(P, zeros(6,4), [0 0], [1 0], 1, 1, bb, 1);
Error in  ft_warp_apply (line 189)
warped = individual2sn(M, input);
########
I want to know how to fix this bug.
Thanks for the great toolbox.
Rongqi lin.

**Comment by schoffelen** [comment]
I think that this has been addressed. Could you upgrade to the latest release version of the toolbox and try again?

**Comment by linrongqi** [comment]
Thank you for your suggestion! I have downloaded the latest version frildtrip-20210325, but the error still here. My code was following.
###### 
mrit1 = ft_read_mri('T1.nii'); 
mrit1.coordsys = 'acpc';

cfg            = [];
cfg.nonlinear  = 'yes';
cfg.spmversion = 'spm12';
cfg.spmmethod  = 'new';
fsmri_mni = ft_volumenormalise(cfg, mrit1);

elec_mni = elec_acpc_fr;
elec_mni.elecpos = ft_warp_apply(fsmri_mni.params, elec_acpc_fr.elecpos, 'individual2sn');
elec_mni.chanpos = ft_warp_apply(fsmri_mni.params, elec_acpc_fr.chanpos, 'individual2sn');
elec_mni.coordsys = 'mni';
##########
#########
Wrong use spm_sample_vol
File too small.
Error in spm_preproc_write8 (line 182)
f = spm_sample_vol(res.image(n),x1,x2,o*x3(z),0);
Error in individual2sn (line 81)
spm_preproc_write8(P, zeros(6,4), [0 0], [1 0], 1, 1, bb, 1);
Error in ft_warp_apply (line 189)
warped = individual2sn(M, input);
###########
The bug still here, my platform was Win10 and matlab 19b.

**Comment by schoffelen** [comment]
I see. Indeed this issue (as also identified by @tiborauer) was fixed for the function sn2individual, but not for individual2sn. @linrongqi please look in the history of sn2individual and feel free to implement the changes that where made there equivalently in individual2sn. Please file this as a new PR. We will then review it, and if approved, merge it

**Comment by schoffelen** [comment]
see #1700

**Comment by linrongqi** [comment]
Thank you for your suggestion!
I have try to fix the error, and i found the error was caused by the 'P.image.dt'.
'P.image.dt' was [64,0]; however, when i use the 'P.image  = spm_vol(fname);'
P.image.dt was [16,0], and i found when i change the P.image.dt  to [16,0], there was no error.(As the Plan 1)
Howerer, when i change the code as the 'sn2individual.m',  'P.image  = spm_vol(fname)', there was also no error.(As the Plan2).
There were two way to fix the error, but I don't know whether the V is necessary, and which one is right?
########
 ft_hastoolbox('spm12', 1);

  fprintf('creating the deformation field and writing it to a temporary file\n');
  bb = spm_get_bbox(P.image(1));
  
  fname  = [tempname,'.nii'];
  V      = nifti;
  V.dat  = file_array(fname, P.image(1).dim(1:3), [spm_type('float32') spm_platform('bigend')], 0, 1, 0);
  V.mat  = P.image(1).mat;
  V.mat0 = P.image(1).mat;
  V.descrip = 'Dummy volume';
  create(V);
  V.dat(:) = 0;
  
  P.image(1).private = V;
  P.image(1).fname   = fname;
  %%  Plan 1
  data.image  = spm_vol(fname);
  P.image.dt  = data.image.dt;
  
  %% Plan 2
  P.image  = spm_vol(fname);
  
  spm_preproc_write8(P, zeros(6,4), [0 0], [1 0], 1, 1, bb, 1);

**Comment by tiborauer** [comment]
I vote for Plan 2 for simplicity and robustness.

**Comment by linrongqi** [comment]
OK,thank you

**Comment by schoffelen** [comment]
I agree with Tibor. An additional argument to go for plan 2 is that it keeps the pair of functions sn2individual and individual2sn consistent with respect to one another. Can I ask you to file a PR for this @linrongqi ?
